account/urls.py
from django.urls import re_path

from . import views

app_name = "account"

urlpatterns = [
    re_path(r"^signup/$", views.user_signup, name="user_signup"),
    re_path(r"^login/$", views.user_login, name="user_login"),
    re_path(r"^logout/$", views.user_logout, name="user_logout"),
]

info/urls.py
from django.urls import re_path
from . import views

app_name = "info"

urlpatterns = [
    re_path("weather/", views.weatherView, name="weather"),
    re_path("set_reminder/", views.setReminderView, name="set_reminder"),
]

website/urls.py
from ast import pattern
from django.contrib import admin
from django.urls import path
from django.urls import re_path, include
# from django.conf import settings

from detector.views import home

urlpatterns = [
    re_path(r"^$", home, name="home"),
    re_path('^admin/', admin.site.urls),
    re_path("^user/", include("account.urls")),
    re_path("^detect/", include("detector.urls")),
    re_path("^get_info/", include("info.urls")),]

templates/login.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign In</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">

    <style>
        .card-signin .card-img-left {
            max-height: 900px;
            width: 50%;
            background: scroll center url("{% static 'images/image.svg' %}");
            background-size: cover;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card card-signin flex-row my-5">
                    <div class="card-body">
                        <h3 class="card-title text-center"><b>Sign In</b></h3>
                        <form class="form-signin" method="post">
                            {% csrf_token %}
                            <button class="btn btn-lg btn-google btn-block" type="submit"><i
                                    class="fab fa-google mr-2"></i> Sign in with Google</button>
                            <button class="btn btn-lg btn-facebook btn-block" type="submit"><i
                                    class="fab fa-facebook-f mr-2"></i> Sign in with Facebook</button>
                            <hr class="my-4">
                            {% for field in form %}
                            <label for="{{field.id}}">{{field.name}}</label>
                            <div class="form-label-group">
                                {{ field }}
                            </div>
                            {% endfor %}
                            <button class="btn btn-lg btn-primary btn-block text-uppercase"
                                type="submit">SignIn</button>
                        </form>
                    </div>
                    <div class="card-img-left d-md-5">
                        <!-- <img src="{% static 'images/Logo.svg' %}" class="image1"> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
</body>

</html>

templates/reminder.html
<html>
    <head>
        <title>Reminders</title>
    </head>

    <body>
        <form method="POST">
            {% csrf_token %}
            {{form}}

            <input type="submit" value="submit">
        </form>
    </body>
</html>

templates/result.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
        integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <title>DISEASE PREDICTION</title>

    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }

        img{
            width: 100%;
            height: 100%;
        }

    </style>
</head>

<body background="{% static 'images/prediction.webp' %}">

    <div>
        <h1 style="text-align:center;font-size:4rem;margin-top:50px;">Predict Skin Disease & Get Cure</h1>
    </div>

   <br>
   <br>


    <div class="container my-2">
        <div class="row mb-5">


            <div class="col-sm" style="margin-bottom: 23px;">
                <span class="border border-primary">

                   {% if category == 0 %}
                    <img src=" {% static 'images/acne.webp' %} " style="width:500px;height:500px;">

                    {% elif category == 1 %}
                    <img src=" {% static 'images/coldsore.png' %} " style="width:500px;height:500px;">

                    {% elif category == 2 %}
                    <img src=" {% static 'images/blister.jpg' %} "style="width:500px;height:500px;">

                    {% elif category == 3 %}
                    <img src=" {% static 'images/hives.webp' %} " style="width:500px;height:500px;">

                    {% elif category == 4 %}
                    <img src=" {% static 'images/keratosis.webp' %} " style="width:500px;height:500px;">

                    {% elif category == 5 %}
                    <img src=" {% static 'images/rosacea.png' %} " style="width:500px;height:500px;">

                    {% elif category == 6 %}
                    <img src=" {% static 'images/carbuncle.jpg' %} " style="width:500px;height:500px;">

                    {% elif category == 7 %}
                    <img src=" {% static 'images/latex.jpeg' %} " style="width:500px;height:500px;">

                    {% elif category == 8 %}
                    <img src=" {% static 'images/eczema.jpg' %} " style="width:500px;height:500px;">

                    {% elif category == 9 %}
                    <img src=" {% static 'images/eczema.jpg' %} " style="width:500px;height:500px;">

                    {% endif %} -->

                </span>
            </div>

            <div class="col-sm">

                <div>
                    <h1 style="padding: 15px; background-color: rgb(15, 15, 15); color: white;"
                        class="text-center mb-5 content-h1 rounded">
                        {{disease}}
                    </h1>
                </div>
                <div class="details" style="margin-top: 50px;">

					<h3><b> Treatment : </b> </h3>
                    <h5 style="margin-top: 30px;">
                        {{remedy}}
                    </br></br>
                    </h5>
                </div>
            </div>
        </div>

    </div>
</body>

</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign Up</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">

    <style>
        .card-signin .card-img-left {
            max-height: 900px;
            width: 50%;
            background: scroll center url("{% static 'images/image.svg' %}");
            background-size: cover;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card card-signin flex-row my-5">
                    <div class="card-body">
                        <h3 class="card-title text-center"><b>Sign Up</b></h3>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-lg btn-google btn-block" type="submit"><i
                                    class="fab fa-google mr-2"></i> Sign up with Google</button>
                            <button class="btn btn-lg btn-facebook btn-block" type="submit"><i
                                    class="fab fa-facebook-f mr-2"></i> Sign up with Facebook</button>
                            <hr class="my-4">
                            {% for field in user_form %}
                            <label for="{{field.id}}">{{field.name}}</label>
                            <div class="form-label-group">
                                {{field}}
                            </div>
                            {% endfor %}
                            {% for field in user_profile_form %}
                            <label for="{{field.id}}">{{field.name}}</label>
                            <div class="form-label-group">
                                {{field}}
                            </div>
                            {% endfor %}
                            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign
                                Up</button>
                            <a class="d-block text-center mt-2 small" href="{% url 'account:user_login' %}">Already have
                                an account? Sign In</a>
                        </form>
                    </div>
                    <div class="card-img-left d-md-5">
                        <!-- <img src="{% static 'images/logo.svg' %}" class="image1"> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/upload_image.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }

        form {
            display: flex;
            height: 85vh;
            justify-content: center;
            align-items: center;
            margin-top: -150px;
            width: 60%;
            text-align: center;
            margin-left: 300px;
        }

        label:hover {
            transform: scale(1.03);
        }

        .details h1 {
            color: white;
            padding: 20px;
            border-radius: 15px;
            background-color: rgb(8, 8, 8);
        }

        .upload {
            font-size: 20px;
            background-color: rgb(255, 252, 252);
            border-radius: 20px;
            outline: none;
            width: 500px;
            color: rgb(0, 0, 0);
            border: 3px solid green;
            padding: 20px;
        }

        ::-webkit-file-upload-button {
            color: green;
            padding: 20px;
            border: 2px solid green;
            background-color: #e9e9e9;
            border-radius: 15px;
            margin-right: 80px;
        }

        ::-webkit-file-upload-text {
            color: rgb(255, 252, 252);
            padding: 20px;
            border: 2px solid green;
            background-color: oldlace;
            border-radius: 15px;
        }

        ::-webkit-file-upload-button:hover {
            border-radius: 20px;
            border: 2px solid rgb(177, 174, 174);
        }

        input[type="submit"] {
            position: absolute;
            margin-top: 300px;
            padding: 15px 35px;
            background-color: rgb(156, 129, 9);
            border-radius: 15px;
            color: black;
            font-size: 1.5rem;
            border: 4px solid rgb(31, 185, 190);
            font-family: Inter;
            border: 3px solid rgb(14, 42, 78);
            color: white;
            opacity: 1;
        }
    </style>
</head>

<!-- {# <body background="{{url_for('static',filename = 'images/detection.jpg')}}"> #} -->
<body background="{% static 'images/logo.png' %}">
    <h1 style="text-align:center;font-size:4rem;margin-top:10%;color: rgb(255, 255, 255);">Predict - wellness and beauty with AlluraSkin Care</h1>
    <section style="background-color: rgb(0, 0, 0,.8); border-radius: 75px;">
        {# <!-- <form action="/predict" method="post" enctype="multipart/form-data" onsubmit="showloading()"> --> #}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {# <!-- <input type="file" name="image" class="upload"> --> #}
            {{ form }}
            <br>
            <br>
            <input type="submit" value="Predict" class="button2">
        </form>
        </div>
    </section>

</body>

</html>

templates/weather.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
        integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <title>WEATHER PREDICTION</title>

    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
            margin: 0;
            /* background-image: url("clouds.jpeg");
            background-repeat: no-repeat; */

            

        }

        .border img {
            border-radius: 15px;
            border: 2px solid black;
        }
        .footer{
            /* background-color: rgba(12, 193, 78, 0.326); */
            margin-top: 20px;
            padding: 100px;
            
        }
        .container{
            z-index: -1;
        }
    </style>
</head>

<body style="background-image:url(clouds.jpeg)" >




        <h4 style=" font-weight:800;font-family:Inter; color:rgb(9, 81, 9); padding: 15px; ; text-align: center;font-size:3rem;margin-top:25px;" >WEATHER PREDICTION</h4>    

   <br>
   <br>

    <div class="container my-2">

        {% for i in forecast %}

        <div class="row mb-2">

            <div class="col-sm-6" >

                <div class="details" style="margin-top: 10px;">
					
					<h5 class=""><b> Date : </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.date}}
                    </br></br>
                    </h5>
                    <h5><b> Min Temparature: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.mintemp_c}}
                    </br></br>
                    </h5>
                    <h5><b> Max Temparature: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.maxtemp_c}}
                    </br></br>
                    </h5>
                    <h5><b> Max Wind Speed(mph): </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.maxwind_mph}}
                    </br></br>
                    </h5>
                    <h5><b> Sunrise: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.Sunrise}}
                    </br></br>
                    </h5>
                    
                </div>
            </div>
            <div class="col-sm-6">

                <div class="details" style="margin-top: 10px;">
                <h5><b> Max Wind Speed(kph): </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.maxwind_kph}}
                    </br></br>
                    </h5>
                    <h5><b> Total Precipitation(mm): </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.totalprecip_mm}}
                    </br></br>
                    </h5>
                    <h5><b> Total Precipitation(in): </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.totalprecip_in}}
                    </br></br>
                    </h5>
                    <h5><b> Total Snow(cm): </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.totalsnow_cm}}
                    </br></br>
                    </h5>
                    <h5><b> Sunset: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{i.forecast.Sunset}}
                    </br></br>
                    </h5>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>

    <!-- <div class="footer"></div> -->
</body>

</html>